# Generated by Django 4.2.1 on 2023-06-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_reviewrating_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
